### ISSUE TITLE
bg-color not uniformly applied for some font widths/heights

### ISSUE THREAD

**Issue by jdtsmith** [rougier/emacs-svg-icon#6]
This looks ideal for user-configured icons, thanks!  I gave it a try and found that extra vertical bars of non-bg color are left on the sides, but only for certain combinations of font-width and font-height:

![image](https://user-images.githubusercontent.com/93749/140860016-b5aa38d1-5cc8-44ce-99e2-143a8fbdf4d9.png)

Update: Even when the vertical bars are absent (at large font sizes), horizontal bars top and bottom get left behind, as seen here:

![image](https://user-images.githubusercontent.com/93749/140861636-c0d82071-dae2-4f69-bb00-64f49865089a.png)

**Comment by rougier** [comment]
Note that this library has been replaced by https://github.com/rougier/svg-lib.

I think the problem comes from the icon not begin exactly the size of a character and the "transparent" part of the icon is replaced byt the background color of your window ('default face). Thi is a recurring problem because Emacs does not really handle transparency in SVG. One fix would be to make sure the icon is exactly the size of a character.

**Comment by jdtsmith** [comment]
Thanks for the pointer.  This issue seems to have been fixed in `svg-lib`:

![image](https://user-images.githubusercontent.com/93749/140940142-8764ac35-feda-4941-a2f7-7de2ca6c149f.png)

Is `:stroke 0` the suggested way to remove the "outline box"?

**Comment by jdtsmith** [comment]
Closing; svg-lib resolves.
